[book]
authors = ["Jimmy Cuadra"]
description = "Guide for the Oxiby programming language."
language = "en"
src = "src"
title = "The Oxiby Programming Language"

[output.html]
additional-js = ["js/highlight.min.js", "js/oxiby.min.js"]
edit-url-template = "https://github.com/oxiby/book/edit/main/{path}"
git-repository-url = "https://github.com/oxiby/book"
